
Halt_On_Error = false
Generate_Log = true
Shader_Files = [ "deferred_frag.glsl", "deferred_vertex.glsl", "geometry_frag.glsl", "geometry_vertex.glsl", "lightsource_frag.glsl", "lightsource_vertex.glsl", "depth_frag.glsl", "depth_vertex.glsl", "shadow_frag.glsl", "shadow_vertex.glsl" ]
GLM_Include = "glm/"
